Remove winmor, add vara
la5nta/pat-website pull request #2
Opened 2022-04-19 15:07 UTC by xylo04

Yes, VARA is still in beta. This is written forward-looking.

I'm not sure what happened to the formatting; the only real changes are on 152-158. This is what the GitHub online editor did. I'll try to revert the superfluous diffs if you'd prefer.

2022-04-19 17:35 UTC, martinhpedersen commented
Please excuse this is a mess: (😅)

This page is actually compiled using a static web page generator called [hugo](https://gohugo.io/). Have a look at the master branch 🙂.

I've tried to update this with a recent version of hugo, but it throws a bunch of warnings and fails. I will boot up an old laptop here and figure out which version we need. Then I'll attempt to dockerize the process. Long term solution is of course to get the source to compile using the a recent version of hugo, or possibly throw away the hole thing and start from scratch with or without a generator.

2022-04-19 18:56 UTC, martinhpedersen requested changes
Done! I've also switched the default branch to `master` and added a quick walkthrough on how to make changes using hugo 🙂 

Please let me know if you have trouble applying your changes using the page generator.

2022-08-21 09:09 UTC, DC7IA commented
The website still mentions WINMOR now that support is removed.

2022-08-21 23:16 UTC, xylo04 commented
Going to start fresh from the `master` branch.

2022-08-21 23:16 UTC, closed without merging